WITH events AS (
  SELECT
    id, type, created_at, repo.name AS repo, actor.login AS event_actor,
    JSON_VALUE(payload, '$.action') AS action,
    CASE
      WHEN type IN ('IssueCommentEvent', 'PullRequestReviewCommentEvent')
        THEN JSON_VALUE(payload, '$.comment.body')
      WHEN type = 'IssuesEvent' AND JSON_VALUE(payload, '$.action') IN ('opened', 'edited')
        THEN JSON_VALUE(payload, '$.issue.body')
      WHEN type = 'PullRequestEvent' AND JSON_VALUE(payload, '$.action') IN ('opened', 'edited')
        THEN JSON_VALUE(payload, '$.pull_request.body')
    END AS body,
    CASE
      WHEN type IN ('IssueCommentEvent', 'PullRequestReviewCommentEvent')
        THEN JSON_VALUE(payload, '$.comment.user.login')
      WHEN type = 'IssuesEvent' THEN JSON_VALUE(payload, '$.issue.user.login')
      WHEN type = 'PullRequestEvent' THEN JSON_VALUE(payload, '$.pull_request.user.login')
    END AS body_author,
    COALESCE(
      JSON_VALUE(payload, '$.comment.html_url'),
      JSON_VALUE(payload, '$.issue.html_url'),
      JSON_VALUE(payload, '$.pull_request.html_url')
    ) AS event_url
  FROM `githubarchive.day.2026*`
  WHERE _TABLE_SUFFIX BETWEEN '0501' AND '0922'
    AND type IN ('IssueCommentEvent', 'IssuesEvent', 'PullRequestEvent',
      'PullRequestReviewCommentEvent')
), candidates AS (
  SELECT *,
    REGEXP_CONTAINS(LOWER(body), r'\b(future agents?|next agent|another agents?|other agents?)\b') AS phrase_hit,
    LOWER(body) LIKE '%gist.github.com%'
      AND REGEXP_CONTAINS(LOWER(body), r'agent|claude|codex|gpt|bot') AS gist_agent_hit,
    REGEXP_EXTRACT_ALL(body, r'https?://(?:www\.)?(?:gist\.)?github\.com/([A-Za-z0-9_.-]+)') AS linked_owners,
    REGEXP_EXTRACT_ALL(body, r'https?://(?:www\.)?(?:gist\.)?github\.com/[^\s)<>"\]]+') AS github_links
  FROM events
  WHERE body IS NOT NULL AND body_author IS NOT NULL
), eligible AS (
  SELECT *,
    ARRAY(SELECT DISTINCT linked_owner FROM UNNEST(linked_owners) AS linked_owner
      WHERE LOWER(linked_owner) != LOWER(SPLIT(repo, '/')[SAFE_OFFSET(0)])
        AND LOWER(linked_owner) != LOWER(body_author)
        AND LOWER(linked_owner) NOT IN ('user-attachments', 'features',
          'settings', 'login', 'signup', 'orgs', 'actions', '...')) AS third_party_owners,
    (IF(REGEXP_CONTAINS(LOWER(body_author), r'agent|bot|claude|codex'), 4, 0)
      + IF(REGEXP_CONTAINS(LOWER(body), r'agent report|agent-generated|generated by.*agent|another agent|other agent'), 3, 0)
      + IF(REGEXP_CONTAINS(LOWER(body), r'https?://github\.com/[^/\s]+/[^/\s]+/(issues|pull)/[0-9]+'), 2, 0)
      + IF(phrase_hit, 1, 0)) AS lead_score
  FROM candidates
  WHERE phrase_hit OR gist_agent_hit
)
SELECT
  id, created_at, type, action, repo, event_actor, body_author, event_url,
  phrase_hit, gist_agent_hit, third_party_owners, lead_score,
  ARRAY(SELECT link FROM UNNEST(github_links) AS link LIMIT 3) AS links,
  SUBSTR(REGEXP_REPLACE(body, r'\s+', ' '), 1, 500) AS excerpt,
  COUNT(*) OVER () AS eligible_count
FROM eligible
WHERE ARRAY_LENGTH(third_party_owners) > 0
QUALIFY ROW_NUMBER() OVER (PARTITION BY repo ORDER BY lead_score DESC, created_at) <= 2
ORDER BY lead_score DESC, created_at
LIMIT 120;
